import { fromEvent } from 'rxjs';
import { map, tap } from 'rxjs/operators';

const text = document.createElement('div');
text.innerHTML = `
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam fermentum sed lorem quis rhoncus. Proin ipsum augue, dictum non erat sed, rhoncus blandit risus. Ut id fermentum nulla. Nulla facilisi. Praesent maximus, magna non rutrum interdum, neque lectus pharetra odio, quis porttitor risus dolor nec sapien. Sed non gravida metus. Donec maximus tristique ex sit amet tempus. Ut tempus pulvinar ex, nec convallis urna. Etiam id auctor sem, at fermentum sapien. Cras neque leo, placerat vel mauris et, pretium tristique massa. Aliquam ac ante est. Mauris quis purus nisl. Praesent vel velit sit amet erat vestibulum elementum. Nunc id dictum nunc. Nulla vel augue ut tellus porta pulvinar eget laoreet sem. Cras semper nibh vel hendrerit accumsan.
    <br/><br/>
    Maecenas scelerisque volutpat est in dapibus. Phasellus tellus elit, hendrerit in euismod non, eleifend vitae enim. Maecenas pretium est a tellus pretium, ut euismod magna rutrum. Suspendisse at tempor sapien. Fusce blandit, ante in elementum feugiat, tortor nibh lacinia tortor, sit amet dapibus sem leo eu risus. Integer facilisis elementum massa sit amet accumsan. In finibus quis tellus eget pellentesque. Ut consequat gravida lacus, eget commodo nunc tempor sed. Nam convallis justo at arcu iaculis tempus. Maecenas auctor fermentum justo, sed aliquam magna. Suspendisse aliquam libero at dictum egestas. Vivamus viverra in enim quis maximus. Fusce consectetur tincidunt magna id mattis. Ut eleifend ex ut erat porta, ut scelerisque mi pulvinar. Fusce quis ullamcorper lorem, quis placerat elit. Mauris justo est, viverra quis faucibus non, venenatis ac lorem.
    <br/><br/>
    In hac habitasse platea dictumst. In lacinia arcu quis tristique pulvinar. Nam ut nunc maximus, tincidunt purus et, bibendum arcu. Vestibulum non ultrices augue. Morbi porttitor, lorem quis dignissim elementum, augue turpis dapibus nulla, ac facilisis lorem turpis ut turpis. Aliquam at ullamcorper libero, egestas aliquam ligula. Morbi sit amet est eros. Ut blandit, augue eget dapibus viverra, ligula urna suscipit ante, in malesuada metus dolor a purus. Sed dui purus, consequat eu nibh vel, sagittis rutrum libero. Praesent est dui, commodo sit amet porttitor vel, iaculis ac ligula. Morbi eleifend urna vel elit dictum, nec mollis nibh tempus. Praesent vel nisl eu leo pharetra viverra. Pellentesque congue ac orci sit amet volutpat. Proin in leo tortor. Donec diam sapien, dignissim non tempor non, pellentesque et erat.
    <br/><br/>
    Fusce odio ante, blandit elementum velit at, gravida semper massa. Proin arcu magna, interdum malesuada magna at, pharetra facilisis diam. Praesent aliquam vestibulum lectus a consectetur. Praesent diam nunc, aliquam quis neque in, blandit bibendum massa. Sed efficitur orci magna, sit amet molestie augue vehicula ut. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam hendrerit mauris nec nibh eleifend, eget euismod ipsum malesuada. Nam non consequat metus, sit amet interdum felis. Duis iaculis velit enim, at vehicula enim pharetra eleifend. Vestibulum luctus turpis turpis, eget aliquet metus tempus id. In viverra purus vel eros laoreet interdum. Aliquam in turpis a odio iaculis pulvinar et a nisi. Vestibulum ultricies, nulla vitae scelerisque venenatis, velit tellus mattis mauris, lacinia luctus purus odio id neque. Integer tempus quam turpis, et aliquet neque pellentesque non.
    <br/><br/>
    Integer non dui at erat feugiat venenatis imperdiet in est. Phasellus finibus mauris est, id venenatis eros auctor sed. Maecenas congue magna eros, nec elementum tortor rutrum in. Curabitur eget ipsum porta, tincidunt sapien sed, consectetur magna. Nulla facilisi. Vivamus aliquam condimentum velit et imperdiet. Aenean vel laoreet enim. Donec molestie neque ac nulla varius, vel pellentesque felis pretium. Pellentesque sollicitudin augue tempus, efficitur diam non, sodales eros. In maximus laoreet sapien, id mattis nisl hendrerit id. Suspendisse potenti. Morbi porta egestas augue, eu iaculis ex dignissim sed. In rhoncus dictum neque, non ultricies velit. Cras ornare elementum dolor, sit amet accumsan est vestibulum quis. Vivamus viverra bibendum sem. Praesent ac commodo ligula, sed rutrum mauris. 
    <br/><br/>    
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam fermentum sed lorem quis rhoncus. Proin ipsum augue, dictum non erat sed, rhoncus blandit risus. Ut id fermentum nulla. Nulla facilisi. Praesent maximus, magna non rutrum interdum, neque lectus pharetra odio, quis porttitor risus dolor nec sapien. Sed non gravida metus. Donec maximus tristique ex sit amet tempus. Ut tempus pulvinar ex, nec convallis urna. Etiam id auctor sem, at fermentum sapien. Cras neque leo, placerat vel mauris et, pretium tristique massa. Aliquam ac ante est. Mauris quis purus nisl. Praesent vel velit sit amet erat vestibulum elementum. Nunc id dictum nunc. Nulla vel augue ut tellus porta pulvinar eget laoreet sem. Cras semper nibh vel hendrerit accumsan.
    <br/><br/>
    Maecenas scelerisque volutpat est in dapibus. Phasellus tellus elit, hendrerit in euismod non, eleifend vitae enim. Maecenas pretium est a tellus pretium, ut euismod magna rutrum. Suspendisse at tempor sapien. Fusce blandit, ante in elementum feugiat, tortor nibh lacinia tortor, sit amet dapibus sem leo eu risus. Integer facilisis elementum massa sit amet accumsan. In finibus quis tellus eget pellentesque. Ut consequat gravida lacus, eget commodo nunc tempor sed. Nam convallis justo at arcu iaculis tempus. Maecenas auctor fermentum justo, sed aliquam magna. Suspendisse aliquam libero at dictum egestas. Vivamus viverra in enim quis maximus. Fusce consectetur tincidunt magna id mattis. Ut eleifend ex ut erat porta, ut scelerisque mi pulvinar. Fusce quis ullamcorper lorem, quis placerat elit. Mauris justo est, viverra quis faucibus non, venenatis ac lorem.
    <br/><br/>
    In hac habitasse platea dictumst. In lacinia arcu quis tristique pulvinar. Nam ut nunc maximus, tincidunt purus et, bibendum arcu. Vestibulum non ultrices augue. Morbi porttitor, lorem quis dignissim elementum, augue turpis dapibus nulla, ac facilisis lorem turpis ut turpis. Aliquam at ullamcorper libero, egestas aliquam ligula. Morbi sit amet est eros. Ut blandit, augue eget dapibus viverra, ligula urna suscipit ante, in malesuada metus dolor a purus. Sed dui purus, consequat eu nibh vel, sagittis rutrum libero. Praesent est dui, commodo sit amet porttitor vel, iaculis ac ligula. Morbi eleifend urna vel elit dictum, nec mollis nibh tempus. Praesent vel nisl eu leo pharetra viverra. Pellentesque congue ac orci sit amet volutpat. Proin in leo tortor. Donec diam sapien, dignissim non tempor non, pellentesque et erat.
    <br/><br/>
    Fusce odio ante, blandit elementum velit at, gravida semper massa. Proin arcu magna, interdum malesuada magna at, pharetra facilisis diam. Praesent aliquam vestibulum lectus a consectetur. Praesent diam nunc, aliquam quis neque in, blandit bibendum massa. Sed efficitur orci magna, sit amet molestie augue vehicula ut. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam hendrerit mauris nec nibh eleifend, eget euismod ipsum malesuada. Nam non consequat metus, sit amet interdum felis. Duis iaculis velit enim, at vehicula enim pharetra eleifend. Vestibulum luctus turpis turpis, eget aliquet metus tempus id. In viverra purus vel eros laoreet interdum. Aliquam in turpis a odio iaculis pulvinar et a nisi. Vestibulum ultricies, nulla vitae scelerisque venenatis, velit tellus mattis mauris, lacinia luctus purus odio id neque. Integer tempus quam turpis, et aliquet neque pellentesque non.
    <br/><br/>
    Integer non dui at erat feugiat venenatis imperdiet in est. Phasellus finibus mauris est, id venenatis eros auctor sed. Maecenas congue magna eros, nec elementum tortor rutrum in. Curabitur eget ipsum porta, tincidunt sapien sed, consectetur magna. Nulla facilisi. Vivamus aliquam condimentum velit et imperdiet. Aenean vel laoreet enim. Donec molestie neque ac nulla varius, vel pellentesque felis pretium. Pellentesque sollicitudin augue tempus, efficitur diam non, sodales eros. In maximus laoreet sapien, id mattis nisl hendrerit id. Suspendisse potenti. Morbi porta egestas augue, eu iaculis ex dignissim sed. In rhoncus dictum neque, non ultricies velit. Cras ornare elementum dolor, sit amet accumsan est vestibulum quis. Vivamus viverra bibendum sem. Praesent ac commodo ligula, sed rutrum mauris. 
`;

const body = document.querySelector('body');
body.append(text);

const progressBar = document.createElement('div');
progressBar.setAttribute('class', 'progress-bar');
body.append(progressBar);

const calculatePercent = (event: any) => {
    const html = event.target.documentElement;
    return (html.scrollTop / (html.scrollHeight - html.clientHeight)) * 100;
};
const scroll$ = fromEvent(document, 'scroll');
const progress$ = scroll$.pipe(
    map(calculatePercent),
    tap(console.log)
);
progress$.subscribe(percent => {
    progressBar.style.width = percent + '%';
});